# Free Cloudflare protection checklist for rexsmp.com
# Run AFTER deploy.ps1 and AFTER adding the site to Cloudflare.

Write-Host ""
Write-Host "=== Cloudflare free protection setup for rexsmp.com ==="
Write-Host ""
Write-Host "1. Go to https://dash.cloudflare.com/sign-up"
Write-Host "2. Add site: rexsmp.com (free plan)"
Write-Host "3. Cloudflare shows 2 nameservers - copy them"
Write-Host "4. At your domain registrar (where you bought .com), replace nameservers with Cloudflare's"
Write-Host "5. In Cloudflare -> DNS -> Records, add:"
Write-Host ""
Write-Host "   Type   Name   Content              Proxy"
Write-Host "   A      @      185.199.108.153      DNS only (grey cloud)"
Write-Host "   A      @      185.199.109.153      DNS only"
Write-Host "   A      @      185.199.110.153      DNS only"
Write-Host "   A      @      185.199.111.153      DNS only"
Write-Host "   CNAME  www    YOUR_GITHUB_USER.github.io   Proxied (orange cloud OK)"
Write-Host ""
Write-Host "   Replace YOUR_GITHUB_USER with output from: gh api user -q .login"
Write-Host ""
Write-Host "6. SSL/TLS -> Overview -> Full"
Write-Host "7. SSL/TLS -> Edge Certificates -> Always Use HTTPS = ON"
Write-Host "8. Security -> Settings:"
Write-Host "      Security Level = Medium or High"
Write-Host "      Browser Integrity Check = ON"
Write-Host "      Bot Fight Mode = ON"
Write-Host "9. Security -> WAF -> Managed rules -> enable free ruleset"
Write-Host "10. Speed -> Optimization -> Auto Minify (JS, CSS, HTML) = ON"
Write-Host ""
Write-Host "11. Add security headers (Rules -> Transform Rules -> Modify Response Header):"
Write-Host "      X-Frame-Options: DENY"
Write-Host "      X-Content-Type-Options: nosniff"
Write-Host "      Referrer-Policy: strict-origin-when-cross-origin"
Write-Host "      Permissions-Policy: camera=(), microphone=(), geolocation=()"
Write-Host "      Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
Write-Host ""
Write-Host "GitHub Pages note: keep root A records on DNS only (grey cloud)."
Write-Host "Orange cloud on @ can break GitHub Pages SSL - use grey for A records."
Write-Host ""
